app/blueprints/bps.py
from flask import Blueprint, redirect, render_template, flash, request, session, url_for, send_file, jsonify
from app.models.tables import Ticket, User, Procedimento, Etapa
from app.models.forms import Tickets, File, Procedimentos, Dep
from datetime import datetime
import json
import requests
import os

import pandas as pd
from datetime import datetime


from app.auth.auth import auth, get_google_provider_cfg, client, GOOGLE_CLIENT_SECRET, GOOGLE_CLIENT_ID

from ..ultils import get_mails_list, insert, del_cat, load, remove_file,\
    save, upload_file, send_mail, filter_by, update_main_reponses, clear_duplicates

from app.ext.db import db

bp_app = Blueprint("bp", __name__)

##
## Views
##

## Endpoint para download do backup, somente admin
@bp_app.route("/save-backup")
def backup():
    backup_file_path = "/home/HelpDeskPython/db.sqlite"
    
    if not session.get("admin"):
        flash("Access denied: Admins only.", "error")
        return redirect(url_for("bp.index"))

    if not os.path.exists(backup_file_path):
        flash("Backup file not found.", "error")
        return redirect(url_for("bp.index"))

    return send_file(backup_file_path, as_attachment=True)

## Endpoint para download das categorias, somente admin
@bp_app.route("/save-cats")
def save_cats():
    backup_file_path = "/home/HelpDeskPython/app/categories.json"
    
    if not session.get("admin"):
        flash("Access denied: Admins only.", "error")
        return redirect(url_for("bp.index"))

    if not os.path.exists(backup_file_path):
        flash("Backup file not found.", "error")
        return redirect(url_for("bp.index"))

    return send_file(backup_file_path, as_attachment=True)

@bp_app.route("/login")
def init_login():
    request_uri = auth()
    return redirect(request_uri)

@bp_app.route("/login/get_user_info")
def get_user_info():
    # Get authorization code Google sent back to you
    code = request.args.get("code")

    # Find out what URL to hit to get tokens that allow you to ask for
    # things on behalf of a user
    google_provider_cfg = get_google_provider_cfg()
    token_endpoint = google_provider_cfg["token_endpoint"]

    # Prepare and send request to get tokens! Yay tokens!
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code,
    )
    
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    # Now that we have tokens (yay) let's find and hit URL
    # from Google that gives you user's profile information,
    # including their Google Profile Image and Email
    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body)

    # We want to make sure their email is verified.
    # The user authenticated with Google, authorized our
    # app, and now we've verified their email through Google!
    if userinfo_response.json().get("email_verified"):
        unique_id = userinfo_response.json()["sub"]
        users_email = userinfo_response.json()["email"]
        picture = userinfo_response.json()["picture"]
        users_name = userinfo_response.json()["given_name"]
    else:
        return "User email not available or not verified by Google.", 400

    # Create a user in our db with the information provided
    # by Google
    user = {
        "id":unique_id, "nome":users_name, "email":users_email, "icon":picture
    }

    icon = user["icon"].split("/")[-1]

    # Send user back to homepage
    return redirect(url_for("bp.create_user", id=user["id"], email=user["email"], nome=user["nome"], icon=icon))

@bp_app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for("bp.login"))

@bp_app.route("/", methods=["GET", "POST"])
def login():
    try:
        if session["id"]:
            if session["admin"]:
                return redirect("/home-admin")
            return redirect("/home")
    except KeyError:
        pass

    return render_template("login.html")

@bp_app.route("/home")
def index():
    try:
        if session["id"]:
            return render_template("index.html", admin=False)
    except KeyError:
        return redirect("/")

@bp_app.route("/home-admin")
def index_admin():
    if session["admin"]:
        return render_template("index.html", admin=True)
    else:
        return redirect("/")

@bp_app.route("/ticket/<id>")
def ticket(id):
    ### Fila de chamados em atendimento
    #Fila de chamados em atendimento ou abertos
    
    ticket = Ticket.query.filter_by(_id=id).first()
    try:
        fila = Ticket.query.filter_by(estado="Em Atendimento").all() + Ticket.query.filter_by(estado="Aberto").all()

        #Ordena a fila por prioridade
        fila = sorted(fila, key=lambda x: x.prioridade)
        
        #posição do chamado na fila
        pos = fila.index(ticket) + 1
        
        ### Fila de chamados em atendimento
    except:
        pos = 0

    return render_template("chamado.html",
    r_user=User.query.filter_by(_id=session["id"]).first().nome,
    admin=session["admin"],
    terceiro = User.query.filter_by(_id=session["id"]).first().terceiro,
    chamado=ticket,
    users = User.query.filter_by(terceiro=True).all() + User.query.filter_by(admin=True).all(),
    pos=pos)

@bp_app.route("/tickets/<filter>")
@bp_app.route("/tickets/")
def tickets(filter=None):
    #Filtra chamados atribuidos para terceiros
    user = User.query.filter_by(_id=session["id"]).first()
    if user.terceiro:
        chamados = Ticket.query.filter_by(att=user.nome).filter(Ticket.estado == "Aberto").all()
        
        return render_template("chamados.html",len=len,list=list,
        chamados=chamados)
    
    if session["admin"]:
        chamados = Ticket.query.all()
    else:
        chamados = User.query.filter_by(_id=session["id"]).first().tickets.all()

        
    if filter:
        chamados = filter_by(chamados, filter)

    if session["admin"]:
        return render_template("chamados.html",len=len,list=list,
            chamados=chamados,
            admin=session["admin"])
    else:
        return render_template("chamados.html",len=len,list=list,
            chamados=chamados)

@bp_app.route("/tickets_close")
def tickets_close(filter=None):
    user = User.query.filter_by(_id=session["id"]).first()
    if user.terceiro:
        chamados = Ticket.query.filter_by(att=user.nome).filter(Ticket.estado == "Fechado").all()
        
        return render_template("chamados.html",len=len,list=list,
        chamados=chamados)

    if session["admin"]:
        chamados = Ticket
        
        chamados = Ticket.query.filter_by(estado="Fechado").all()
            
        return render_template("chamados.html",len=len,list=list,
            chamados=chamados,
            admin=session["admin"])

    return render_template("chamados.html",len=len,list=list,
    chamados=User.query.filter_by(_id=session["id"]).first().tickets.filter(Ticket.estado == "Fechado").all())

@bp_app.route("/tickets_resol")
def tickets_resol(filter=None):
    user = User.query.filter_by(_id=session["id"]).first()
    if user.terceiro:
        chamados = Ticket.query.filter_by(att=user.nome).filter(Ticket.estado == "Em Atendimento").all()
        
        return render_template("chamados.html",len=len,list=list,
        chamados=chamados)

    if session["admin"]:
        chamados = Ticket
        
        chamados = Ticket.query.filter_by(estado="Em Atendimento").all()

        return render_template("chamados.html",len=len,list=list,
            chamados=chamados,
            admin=session["admin"])

    
    return render_template("chamados.html",len=len,list=list,
    chamados=User.query.filter_by(_id=session["id"]).first().tickets.filter(Ticket.estado == "Em Atendimento").all())


@bp_app.route("/base_create", methods=["POST", "GET"])
def base_create():
    if request.method == "POST":
        if session["admin"]:    
            data = Procedimento()
            form = Procedimentos()
            if form.validate_on_submit():
                form.populate_obj(data)
                db.session.add(data)
                db.session.commit()
                flash("Procedimento criado com sucesso")
            return redirect("/home-admin")

        flash("Apenas administradores podem criar procedimentos")
        return redirect("/home")
    return render_template("create_base.html", form=Procedimentos())

@bp_app.route("/base_content/<id>")
def base_content(id):
    proc = Procedimento().query.filter_by(_id=id).first()

    return render_template("base_content.html",
    enumerate=enumerate,
    proc=proc,
    etapas=proc.procedimento.split(" "), admin=session["admin"])

@bp_app.route("/base_list")
def base_list():
    return render_template("base_list.html", procs=Procedimento.query.all())

@bp_app.route("/create_ticket", methods=["POST", "GET"])
def create_ticket():
    if request.method == "POST":
        data = Ticket()
        form_cad = Tickets()
        file = File()

        form = request.form

        user = User.query.filter_by(_id=session["id"]).first()
        username = user.nome
        userdep = user.dep

        if form_cad.validate_on_submit() and file.validate_on_submit():
            form_cad.populate_obj(data)
            data.prioridade = 0
            data.ativo = request.form["ativo"]
            data.autor = username
            data.dep = userdep
            data.data_hora_a = datetime.today()
            data.file = upload_file(file.file.data, "static/files/anexos")
            data.user_id = session["id"]
            db.session.add(data)
            db.session.commit()
            

app/templates/base_list.html
<body>
    <div class="fade-in-image">

        <h1 class="title">
            Procedimentos:
    </h1>
    <div class="usuarios">
        {%for proc in procs%}
        <div class="card card-body">
                <a href="#" id="{{proc._id}}">
                    <p>
                        Titulo: {{proc.titulo}}
                    </p>
                </a>     
        </div>
        {%endfor%}
    </div>
    
    <script>
        {% for proc in procs%}
            document.getElementById("{{proc._id}}").onclick = function (){
            const update_url = {{ url_for("bp.base_content", id=proc._id)|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#forms").html(text))
        }
        
        {%endfor%}
        </script>
        </div>
</body>

app/templates/chamados.html
<!DOCTYPE html>
<html lang="pt-br">
<body>
    <div class="fade-in-image">

        <h1 class="title">
        <div class="ch" id="title-ch">
            Niveis de Atendimento:
        </div>
    </h1>
    <div class="chamados">
        <div class="prioridade">
            <p id="menu-cats">
                <a class="btn btn-primary pri" id="show-eme">
                    Emergencia ({{ chamados|selectattr('prioridade', 'eq', 1)|list|length }})
                    <span class="bem"></span>
                </a>
                <a class="btn btn-primary pri" id="show-urg">
                    Urgente ({{ chamados|selectattr('prioridade', 'eq', 2)|list|length }})
                    <span class="bu"></span>
                </a>
                <a class="btn btn-primary pri" id="show-nm">
                    Normal ({{ chamados|selectattr('prioridade', 'eq', 3)|list|length }})
                    <span class="bpu"></span>
                </a>
                <a class="btn btn-primary pri " id="show-nurg">
                    Não urgente ({{ chamados|selectattr('prioridade', 'eq', 4)|list|length }})
                    <span class="bnu"></span>
                </a>
            </p>
            <div>
                <div class="card card-body overflow" id="eme">
                    {%for chamado in chamados%}
                    {%if admin%}
                    {%if chamado.prioridade == 1 and chamado.p_defined == "1"%}
                    
                        <a href="#" class="cat" id="ch-{{chamado._id}}">
                            <p>
                                Problema: {{chamado.problema}}
                            </p>
                            <p>
                                Status: {{chamado.estado}}
                            </p>
                            <p>
                                Aberto por: {{chamado.autor}}
                            </p>
                        </a>
                    {%endif%} 
                    {%else%}
                    {%if chamado.prioridade == 1%}
                    <a href="#" class="cat" id="ch-{{chamado._id}}">
                        <p>
                            Problema: {{chamado.problema}}
                        </p>
                        <p>
                            Status: {{chamado.estado}}
                        </p>
                        <p>
                            Aberto por: {{chamado.autor}}
                        </p>
                    </a>
                    {%endif%}
                    {%endif%}
                {%endfor%}
                </div>
                <div class="card card-body overflow" id="urg">
                    {%for chamado in chamados%}
                    {%if admin%}
                    {%if chamado.prioridade == 2 and chamado.p_defined == "1"%}
                        <a href="#" class="cat" id="ch-{{chamado._id}}">
                            <p>
                                Problema: {{chamado.problema}}
                            </p>
                            <p>
                                Status: {{chamado.estado}}
                            </p>
                            <p>
                                Aberto por: {{chamado.autor}}
                            </p>

                        </a>
                    {%endif%} 
                    {%else%}
                    {%if chamado.prioridade == 2%}
                    <a href="#" class="cat" id="ch-{{chamado._id}}">
                        <p>
                            Problema: {{chamado.problema}}
                        </p>
                        <p>
                            Status: {{chamado.estado}}
                        </p>
                        <p>
                            Aberto por: {{chamado.autor}}
                        </p>

                    </a>
                    {%endif%}
                    {%endif%}
                {%endfor%}
                </div>
                <div class="card card-body overflow" id="norm">
                    {%for chamado in chamados%}
                    {%if admin%}
                    {%if chamado.prioridade == 3 and chamado.p_defined == "1"%}
                        <a href="#" class="cat" id="ch-{{chamado._id}}">
                            <p>
                                Problema: {{chamado.problema}}
                            </p>
                            <p>
                                Status: {{chamado.estado}}
                            </p>
                            <p>
                                Aberto por: {{chamado.autor}}
                            </p>

                        </a>
                        {%endif%}
                        {%else%}
                        {%if chamado.prioridade == 3%}
                        <a href="#" class="cat" id="ch-{{chamado._id}}">
                            <p>
                                Problema: {{chamado.problema}}
                            </p>
                            <p>
                                Status: {{chamado.estado}}
                            </p>
                            <p>
                                Aberto por: {{chamado.autor}}
                            </p>

                        </a>
                        {%endif%}
                        {%endif%}
                        {%endfor%}
                </div>
                <div class="card card-body overflow" id="purg">
                    {%for chamado in chamados%}
                    {%if admin%}
                    {%if chamado.prioridade == 4 and chamado.p_defined == "1"%}
                        <a href="#" class="cat" id="ch-{{chamado._id}}">
                            <p>
                                Problema: {{chamado.problema}}
                            </p>
                            <p>
                                Status: {{chamado.estado}}
                            </p>
                            <p>
                                Aberto por: {{chamado.autor}}
                            </p>

                        </a>
                        {%endif%}
                        {%else%}
                        {%if chamado.prioridade == 4%}
                        <a href="#" class="cat" id="ch-{{chamado._id}}">
                            <p>
                                Problema: {{chamado.problema}}
                            </p>
                            <p>
                                Status: {{chamado.estado}}
                            </p>
                            <p>
                                Aberto por: {{chamado.autor}}
                            </p>

                        </a>
                        {%endif%}
                        {%endif%}
                        {%endfor%}
                </div>
            </div>
        </div>
          
    </div>
    <script>
        $("#eme").hide();
        $("#urg").hide();
        $("#norm").hide();
        $("#purg").hide();

        $("#show-eme").click(() => {
            $("#eme").show();
            $("#urg").hide();
            $("#norm").hide();
            $("#purg").hide();
        })

        $("#show-urg").click(() => {
            $("#eme").hide();
            $("#urg").show();
            $("#norm").hide();
            $("#purg").hide();
        })

        $("#show-nm").click(() => {
            $("#eme").hide();
            $("#urg").hide();
            $("#norm").show();
            $("#purg").hide();
        })
        
        $("#show-nurg").click(() => {
            $("#eme").hide();
            $("#urg").hide();
            $("#norm").hide();
            $("#purg").show();
        })

        {% for chamado in chamados%}
        try {
            document.getElementById("ch-{{chamado._id}}").onclick = function (){
            const update_url = {{ url_for("bp.ticket", id=chamado._id)|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#forms").html(text)).then(() => {
                $("#hist-data").hide()
            }
            )
            }
        } catch (error) {
            
        }

        {%endfor%}
    </script>

<script>
    // Add active class to the current button (highlight it)
    var header = document.getElementById("menu-cats");
    var btns = header.getElementsByClassName("pri");
    for (var i = 0; i < btns.length; i++) {
      btns[i].addEventListener("click", function() {
      var current = document.getElementsByClassName("active-pri");
      if (current.length > 0) { 
        current[0].className = current[0].className.replace(" active-pri", "");
      }
      this.className += " active-pri";
      });
    }
    </script>
</div>
</body>
</html>

app/templates/create_cat.html
<div class="ctickets">
    <h1 class="title">
        Criar Nova Categoria:
    </h1>
    <form method="post" enctype="multipart/form-data">
        <input type="text" name="cat" class="form-control tcad" placeholder="Categoria">
        <input type="text" name="sub" class="form-control tcad" placeholder="Sub Categoria">
        
        <div class="input-group-append input">
            <button class="btn btn-primary" type="submit" formaction="/create_cat">Enviar</button>
        </div>
    </form>
    
</div>

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/index.css">
    <link rel="stylesheet" href="static/css/chamados.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <!-- Plotly -->
    <script src="https://cdn.plot.ly/plotly-3.0.0.min.js" charset="utf-8"></script>

    <!-- Include html2canvas -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
    <!-- Include jsPDF -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
    </head>

    <title>HelpDesk</title>
</head>
<body>

    <div class="container-fluid slider rotate">
        <div class="row">
            <div class="col-2 block" id="options">
                
                <div class="menu" id="menu">
                    <div id="userlat">

                    </div>
                    <a class="nav-item nav-link nav-item-click nav" id="cham" href="#">Chamados Em Aberto</a>
                    
                    <a class="nav-item nav-link nav-item-click nav" id="chamr" href="#">Em Atendimento</a>
                    <a class="nav-item nav-link nav-item-click nav" id="chamf" href="#">Historico de Chamados</a>
                    
                    {%if admin%}
                        <a class="nav-item nav-link nav-item-click nav" id="base" href="#">Base de Conhecimento</a>
                        <a class="nav-item nav-link nav-item-click nav" id="cuser" href="#">Gereciar Usuarios</a>
                        <a class="nav-item nav-link nav-item-click nav" id="ccat" href="#">Criar Categoria</a>
                        <a class="nav-item nav-link nav-item-click" id="dash" href="#">Dashboard</a>
                    {%endif%}
                    
                    <a class="nav-item nav-link nav-item-click" id="sair" href="/logout">Sair</a>
                </div>
            </div>

            <div class="col block" id="root">
                {%set messages = get_flashed_messages()%}
                {%if messages%}
                    {%for msg in messages%}
                        <div class="alert alert-light">{{msg}}</div>
                    {%endfor%}
                {%endif%}
            </div>

            <div class="col-4 block" id="forms">
                
            </div>
        </div>
    </div>

    <div class="modal fade" id="confirmationModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirmação</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    Tem certeza que deseja excluir o item?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="confirmFollow">OK</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        //On Page Load
        fetch({{ url_for("bp.view_user_lateral")|tojson }})
            .then(response => response.text())
            .then(text => $("#userlat").html(text))

        document.getElementById("cham").onclick = function (){

            const update_url = {{ url_for("bp.tickets")|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#root").html(text))

            fetch({{ url_for("bp.create_ticket")|tojson }})
            .then(response => response.text())
            .then(text => $("#forms").html(text))
        }

        {%if admin%}
        document.getElementById("cuser").onclick = function (){
            const update_url = {{ url_for("bp.view_users")|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#root").html(text))

            $("#forms").html("")
        }

        document.getElementById("ccat").onclick = function (){
            const update_url = {{ url_for("bp.cats")|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#root").html(text))

            fetch({{ url_for("bp.create_cat")|tojson }})
            .then(response => response.text())
            .then(text => $("#forms").html(text))
        }

        document.getElementById("base").onclick = function (){
            const update_url = {{ url_for("bp.base_list")|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#root").html(text))

            fetch({{ url_for("bp.base_create")|tojson }})
            .then(response => response.text())
            .then(text => $("#forms").html(text))
        }


        {%endif%}

        document.getElementById("chamf").onclick = function (){

            const update_url = {{ url_for("bp.tickets_close")|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#root").html(text))

            fetch({{ url_for("bp.create_ticket")|tojson }})
            .then(response => response.text())
            .then(text => $("#forms").html(text))
        }

        document.getElementById("chamr").onclick = function (){

            const update_url = {{ url_for("bp.tickets_resol")|tojson }}

            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#root").html(text))
            
            fetch({{ url_for("bp.create_ticket")|tojson }})
            .then(response => response.text())
            .then(text => $("#forms").html(text))
        }
    
        document.getElementById("dash").onclick = function () {
            const button = this; // Reference to the clicked button
            const update_url = {{ url_for("bp.dashboard")|tojson }};

            // Add loading class to the button
            button.classList.add("loading");

            fetch(update_url)
                .then(response => response.text())
                .then(text => {
                    // Update the content of the root element
                    $("#root").html(text);
                })
                .then(() => {
                    // Hide the forms
                    $("#forms").hide();
                })
                .finally(() => {
                    // Remove the loading class after the content is loaded
                    button.classList.remove("loading");
                });
        };

        $(".nav").click(() => {
            $("#forms").show()
        })

    </script>

<script>
    // Add active class to the current button (highlight it)
    var header = document.getElementById("menu");
    var btns = header.getElementsByClassName("nav-item-click");
    for (var i = 0; i < btns.length; i++) {
      btns[i].addEventListener("click", function() {
      var current = document.getElementsByClassName("active");
      if (current.length > 0) { 
        current[0].className = current[0].className.replace(" active", "");
      }
      this.className += " active";
      });
    }

    function confirm_link(url) {
        let linkToFollow = null;
    
        linkToFollow = url // Store the link URL
        $('#confirmationModal').modal('show'); // Show the modal
    
        $('#confirmFollow').on('click', function() {
            window.location.href = linkToFollow; // Follow the link if confirmed
        });
    }
    </script>
    
</body>
</html>

app/templates/view_user_lat.html

<div style="display:flex; flex-direction:column; padding: 0.3rem;">
    <style>
        .popup-container {
            position: relative;
            display: inline-block;
            margin: 0;
        }

        .popup-content {
            display: none;
            position: absolute;
            padding: 0;
            margin: 0;
            border-radius: 5px;
            z-index: 1;
            top: 25px;
        }
        
        .popup-container:hover .popup-content {
            display: block;
        }

        ul {
            list-style-type: none;
            padding: 0;
            margin:0;
            border-radius: 8px;
        }

        li {
            padding: 10px;
            transition: background-color 0.3s;
            user-select: none;
        }

        li:hover {
            background-color: #ddd;
        }

        option:hover{
            background-color: #ddd;
        }
        
        .selected {
            background-color: #ddd;
        }

    </style>

    <div style="display: flex;flex-direction: row;justify-content: space-around; padding: 0.2rem;">
        <div style="display:flex; flex-direction:column; padding: 0.3rem;">
            <p>
                {{user.nome}}
            </p>
            <p>
                {{user.dep}}
            </p>
        </div>
        <img src="{{user.file}}" alt="user icon" style="width: 3.5rem; height: 3.5rem; border-radius: 50%; padding: 0.3rem;">
    </div>
    <div style="display: flex;flex-direction: row;" class="popup-container tcad">
        <div style="display: flex;flex-direction: row;">
            <input type="text" class="srch" id="search">
        </div>
        
        <script>

        $('#search').change(() => {
            // Get the filter value from the search input
            let filter = $("#search").val().toLowerCase(); // Convert to lowercase for case-insensitive search

            
            const update_url = {{ url_for("bp.tickets")|tojson }}+filter 
            
            fetch(update_url)
            .then(response => response.text())
            .then(text => $("#root").html(text))
            
        });
        </script>
    </div>
</div>